Models/Message_ViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Models
{
    public class Message_ViewModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string NameFamily { get; set; }
        [Required]
        public string Subject { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string UserMessage { get; set; }
        [Required]   
        public string Time { get; set; }       
    }
}

Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Models ;
using System.Globalization;
using My_Project.Context;
using ExtensionMethod;

namespace My_Project.Controllers
{
    public class ResultController : Controller
    {
        readonly My_ProjectContext db;
        public ResultController( My_ProjectContext _db)
        {
            db = _db;
        }

        public IActionResult Index(int id)
        {
            if (id == 0)
            {
                ViewBag.er = " خطا در ورود ...! ";
            }

            return View();
        }

        public IActionResult Set_Password(Login_ViewModel login_vm)
        {
            if (login_vm.UserName == "1" && login_vm.Password == "1")
            {
                return RedirectToAction("Menu");
            }
            else
            {
                return RedirectToAction("Index" , new{ id = 0 });
            }
        }

        public IActionResult Menu()
        {
            return View();
        }

        public IActionResult Message()
        {
            var msg = db.Tbl_Message.OrderByDescending(n => n.Id).ToList();
            List<Message_ViewModel> l_msg = new List<Message_ViewModel>();

            foreach (var item in msg)
            {
                Message_ViewModel msg_vm = new Message_ViewModel
                {
                    NameFamily = item.NameFamily,
                    Email = item.Email,
                    Subject = item.Subject,
                    UserMessage = item.UserMessage,
                    Time = item.Time.ToPersianDateTime() ,
                };

                l_msg.Add(msg_vm);
            }

            return View(l_msg);
        }

        public IActionResult SignUp()
        {
            var user = db.Tbl_User.OrderByDescending(n => n.Id).ToList();
            List<User_ViewModel> l_user = new List<User_ViewModel>();

            foreach (var item in user)
            {
                User_ViewModel user_vm = new User_ViewModel
                {
                    Name = item.Name,
                    Family = item.Family,
                    Email = item.Email,
                    Age = item.Age,
                    NationalCode = item.NationalCode,
                    Education = item.Education,
                    PhoneNumber = item.PhoneNumber,
                    Time = item.Time.ToPersianDateTime(),
                };

                l_user.Add(user_vm);
            }

            return View(l_user);
        }

    }
}

Views/Result/Index.cshtml
@{ 
	Layout = "_Layout2"; 
	@model Models.Login_ViewModel
}

<div class="container">
	<div class="screen">
		<div class="screen__content">
			<form class="login" asp-controller="Result" asp-action="Set_Password" autocomplete="off">	
          		<div class="col-12" dir="rtl">
            		@if (ViewBag.er != null)
            		{
            		    <div class="my-1 col-12 text-center">
            		        <p class="alert alert-danger"> @ViewBag.er </p>
            		    </div>
            		}
          		</div>
				<div class="login__field">
					<i class="login__icon fas fa-user"></i>
					<input type="text" class="login__input" placeholder="User name" asp-for="UserName" required>
				</div>
				<div class="login__field">
					<i class="login__icon fas fa-lock"></i>
					<input type="password" class="login__input" placeholder="Password" asp-for="Password" required>
				</div>
				<button class="button login__submit" type="submit">
					<span class="button__text">Log In Now</span>
					<i class="button__icon fas fa-chevron-right"></i>
				</button>
			</form>
			@* <div class="social-login">
				<h3>log in via</h3>
				<div class="social-icons">
					<a href="#" class="social-login__icon fab fa-instagram"></a>
					<a href="#" class="social-login__icon fab fa-facebook"></a>
					<a href="#" class="social-login__icon fab fa-twitter"></a>
				</div>
			</div> *@
		</div>
		<div class="screen__background">
			<span class="screen__background__shape screen__background__shape4"></span>
			<span class="screen__background__shape screen__background__shape3"></span>
			<span class="screen__background__shape screen__background__shape2"></span>
			<span class="screen__background__shape screen__background__shape1"></span>
		</div>
	</div>
</div>

Views/Result/Menu.cshtml
@{ 
	Layout = "_Layout2";
}

<div class="container">
    <div class="row text-center">
        <a class="btn btn-danger btn-lx" href="/Result/Message"> پیام ها </a>
        <a class="btn btn-danger btn-lx" href="/Result/SignUp"> ثبت نام ها </a>
    </div>
</div>

Views/Result/Message.cshtml
@{ 
  Layout = "_Layout2";
  @model IEnumerable<Models.Message_ViewModel>
}
<div class="container text-center">
    <table class="table table-hover table-bordered">
      <thead class="bg-dark">
        <tr>
          <th class="text-center"> ردیف </th>
          <th class="text-center"> نام و نام خانوادگی </th>
          <th class="text-center"> موضوع </th>
          <th class="text-center"> تاریخ </th>
          <th class="text-center"> ایمیل </th>
          <th class="text-center" rows="2"> پیام </th>
        </tr>
      </thead>
      <tbody>
        @foreach (var item in Model)
        {
            int i = 1 ;
            <tr>
              <td>@i</td>
              <td>@item.NameFamily</td>
              <td>@item.Subject</td>
              <td>@item.Time</td>
              <td>@item.Email</td>
              <td>@item.UserMessage</td>
            </tr>
            i++; 
        }
      </tbody>
    </table>
</div>

Views/Result/SignUp.cshtml
@{ 
	Layout = "_Layout2";
  @model IEnumerable<Models.User_ViewModel>
}
<div class="container text-center">
    <table class="table table-hover table-bordered">
      <thead class="bg-dark">
        <tr>
          <th class="text-center"> ردیف </th>
          <th class="text-center"> نام و نام خانوادگی </th>
          <th class="text-center"> سن </th>
          <th class="text-center"> کدملی </th>
          <th class="text-center"> تحصیلات </th>
          <th class="text-center"> شماره تلفن </th>
          <th class="text-center"> ایمیل </th>
          <th class="text-center"> تاریخ ثبت نام </th>
        </tr>
      </thead>
      <tbody>
        @foreach (var item in Model)
        {
            int i = 1 ;
            <tr>
              <td>@i</td>
              <td>@item.Name @item.Family</td>
              <td>@item.Age</td>
              <td>@item.NationalCode</td>
              <td>@item.Education</td>
              <td>@item.PhoneNumber</td>
              <td>@item.Email</td>
              <td>@item.Time</td>
            </tr>
            i++; 
        }
      </tbody>
    </table>
</div>